import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'
import SampleBox from "components/SampleBox";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import SampleFBXModel from "components/SampleFBXModel";
import SampleVRMModel from "components/SampleVRMModel";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <div className={styles.screen}>
          <Canvas>
            <SampleFBXModel/>
            <SampleVRMModel/>
            <SampleBox/>
            <OrbitControls/>
            <gridHelper/>
            <directionalLight position={[1, 1, 1]}/>
          </Canvas>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>
  )
}
