/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_Mesh_head_geo001_lambert2SG001: THREE.Mesh
  }
  materials: {
    ['lambert2SG.001']: THREE.MeshStandardMaterial
  }
}

export default function KerRingLetters({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/key-ring-letters.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_Mesh_head_geo001_lambert2SG001.geometry}
          material={materials['lambert2SG.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/key-ring-letters.glb')
